# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FrameworkApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FrameworkApp

  #通用
  pod 'ObjectMapper'
  pod 'MBProgressHUD'

  # 网络
  pod 'Alamofire'
  
  # RX
  pod 'RxSwift'
  pod 'RxCocoa'
  
  
end
